--Insertar a la tabla ATAQUE
INSERT ALL
INTO ATAQUE VALUES (1, 'Destructor', 'Ataque físico', 40, 100, 35, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (2, 'Golpe Kárate', 'Ataque físico', 50, 100, 25, 'Has an increased chance for a critical hit.', 2)
INTO ATAQUE VALUES (3, 'Doble Bofetón', 'Ataque físico', 15, 85, 10, 'Hits 2-5 times in one turn.', 1)
INTO ATAQUE VALUES (4, 'Puño Cometa', 'Ataque físico', 18, 85, 15, 'Hits 2-5 times in one turn.', 1)
INTO ATAQUE VALUES (5, 'Megapuño', 'Ataque físico', 80, 85, 20, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (6, 'Día de Pago', 'Ataque físico', 40, 100, 20, 'Scatters money on the ground worth five times the users level.', 1)
INTO ATAQUE VALUES (7, 'Puño Fuego', 'Ataque físico', 75, 100, 15, 'Has a 10% chance to burn the target.', 9)
INTO ATAQUE VALUES (8, 'Puño Hielo', 'Ataque físico', 75, 100, 15, 'Has a 10% chance to freeze the target.', 14)
INTO ATAQUE VALUES (9, 'Puño Trueno', 'Ataque físico', 75, 100, 15, 'Has a 10% chance to paralyze the target.', 12)
INTO ATAQUE VALUES (10, 'Arañazo', 'Ataque físico', 40, 100, 35, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (11, 'Agarre', 'Ataque físico', 55, 100, 30, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (12, 'Guillotina', 'Ataque físico', null, 30, 5, 'Causes a one-hit KO.', 1)
INTO ATAQUE VALUES (13, 'Viento Cortante', 'Ataque especial', 80, 100, 10, 'Requires a turn to charge before attacking.', 1)
INTO ATAQUE VALUES (14, 'Danza Espada', 'Ataque especial', null, null, 20, 'Raises the users Attack by two stages.', 1)
INTO ATAQUE VALUES (15, 'Corte', 'Ataque físico', 50, 95, 30, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (16, 'Tornado', 'Ataque especial', 40, 100, 35, 'Inflicts regular damage and can hit Pokémon in the air.', 3)
INTO ATAQUE VALUES (17, 'Ataque Ala', 'Ataque físico', 60, 100, 35, 'Inflicts regular damage with no additional effect.', 3)
INTO ATAQUE VALUES (18, 'Remolino', 'Ataque especial', null, null, 20, 'Immediately ends wild battles.  Forces trainers to switch Pokémon.', 1)
INTO ATAQUE VALUES (19, 'Vuelo', 'Ataque físico', 90, 95, 15, 'User flies high into the air, dodging all attacks, and hits next turn.', 3)
INTO ATAQUE VALUES (20, 'Atadura', 'Ataque físico', 15, 85, 20, 'Prevents the target from fleeing and inflicts damage for 2-5 turns.', 1)
INTO ATAQUE VALUES (21, 'Atizar', 'Ataque físico', 80, 75, 20, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (22, 'Látigo Cepa', 'Ataque físico', 45, 100, 25, 'Inflicts regular damage with no additional effect.', 11)
INTO ATAQUE VALUES (23, 'Pisotón', 'Ataque físico', 65, 100, 20, 'Has a 30% chance to make the target flinch.', 1)
INTO ATAQUE VALUES (24, 'Doble Patada', 'Ataque físico', 30, 100, 30, 'Hits twice in one turn.', 2)
INTO ATAQUE VALUES (25, 'Megapatada', 'Ataque físico', 120, 75, 5, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (26, 'Patada Salto', 'Ataque físico', 100, 95, 10, 'If the user misses, it takes half the damage it would have inflicted in recoil.', 2)
INTO ATAQUE VALUES (27, 'Patada Giro', 'Ataque físico', 60, 85, 15, 'Has a 30% chance to make the target flinch.', 2)
INTO ATAQUE VALUES (28, 'Ataque Arena', 'Ataque especial', null, 100, 15, 'Lowers the targets accuracy by one stage.', 5)
INTO ATAQUE VALUES (29, 'Golpe Cabeza', 'Ataque físico', 70, 100, 15, 'Has a 30% chance to make the target flinch.', 1)
INTO ATAQUE VALUES (30, 'Cornada', 'Ataque físico', 65, 100, 25, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (31, 'Ataque Furia', 'Ataque físico', 15, 85, 20, 'Hits 2-5 times in one turn.', 1)
INTO ATAQUE VALUES (32, 'Perforador', 'Ataque físico', null, 30, 5, 'Causes a one-hit KO.', 1)
INTO ATAQUE VALUES (33, 'Placaje', 'Ataque físico', 50, 100, 35, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (34, 'Golpe Cuerpo', 'Ataque físico', 85, 100, 15, 'Has a 30% chance to paralyze the target.', 1)
INTO ATAQUE VALUES (35, 'Constricción', 'Ataque físico', 15, 90, 20, 'Prevents the target from fleeing and inflicts damage for 2-5 turns.', 1)
INTO ATAQUE VALUES (36, 'Derribo', 'Ataque físico', 90, 85, 20, 'User receives 1/4 the damage it inflicts in recoil.', 1)
INTO ATAQUE VALUES (37, 'Golpe', 'Ataque físico', 120, 100, 10, 'Hits every turn for 2-3 turns, then confuses the user.', 1)
INTO ATAQUE VALUES (38, 'Doble Filo', 'Ataque físico', 120, 100, 15, 'User receives 1/3 the damage inflicted in recoil.', 1)
INTO ATAQUE VALUES (39, 'Látigo', 'Ataque especial', null, 100, 30, 'Lowers the targets Defense by one stage.', 1)
INTO ATAQUE VALUES (40, 'Picotazo Ven', 'Ataque físico', 15, 100, 35, 'Has a 30% chance to poison the target.', 4)
INTO ATAQUE VALUES (41, 'Doble Ataque', 'Ataque físico', 25, 100, 20, 'Hits twice in the same turn.  Has a 20% chance to poison the target.', 7)
INTO ATAQUE VALUES (42, 'Pin Misil', 'Ataque físico', 25, 95, 20, 'Hits 2-5 times in one turn.', 7)
INTO ATAQUE VALUES (43, 'Malicioso', 'Ataque especial', null, 100, 30, 'Lowers the targets Defense by one stage.', 1)
INTO ATAQUE VALUES (45, 'Gruñido', 'Ataque especial', null, 100, 40, 'Lowers the targets Attack by one stage.', 1)
INTO ATAQUE VALUES (46, 'Rugido', 'Ataque especial', null, null, 20, 'Immediately ends wild battles.  Forces trainers to switch Pokémon.', 1)
INTO ATAQUE VALUES (47, 'Canto', 'Ataque especial', null, 55, 15, 'Puts the target to sleep.', 1)
INTO ATAQUE VALUES (48, 'Supersónico', 'Ataque especial', null, 55, 20, 'Confuses the target.', 1)
INTO ATAQUE VALUES (49, 'Bomba Sónica', 'Ataque especial', null, 90, 20, 'Inflicts 20 points of damage.', 1)
INTO ATAQUE VALUES (50, 'Anulación', 'Ataque especial', null, 100, 20, 'Disables the targets last used move for 1-8 turns.', 1)
INTO ATAQUE VALUES (51, 'Ácido', 'Ataque especial', 40, 100, 30, 'Has a 10% chance to lower the targets Ataque especial Defense by one stage.', 4)
INTO ATAQUE VALUES (52, 'Ascuas', 'Ataque especial', 40, 100, 25, 'Has a 10% chance to burn the target.', 9)
INTO ATAQUE VALUES (53, 'Lanzallamas', 'Ataque especial', 90, 100, 15, 'Has a 10% chance to burn the target.', 9)
INTO ATAQUE VALUES (54, 'Neblina', 'Ataque especial', null, null, 30, 'Protects the users stats from being changed by enemy moves.', 14)
INTO ATAQUE VALUES (55, 'Pistola Agua', 'Ataque especial', 40, 100, 25, 'Inflicts regular damage with no additional effect.', 10)
INTO ATAQUE VALUES (56, 'Hidrobomba', 'Ataque especial', 110, 80, 5, 'Inflicts regular damage with no additional effect.', 10)
INTO ATAQUE VALUES (57, 'Surf', 'Ataque especial', 90, 100, 15, 'Inflicts regular damage and can hit Dive users.', 10)
INTO ATAQUE VALUES (58, 'Rayo Hielo', 'Ataque especial', 90, 100, 10, 'Has a 10% chance to freeze the target.', 14)
INTO ATAQUE VALUES (59, 'Ventisca', 'Ataque especial', 110, 70, 5, 'Has a 10% chance to freeze the target.', 14)
INTO ATAQUE VALUES (60, 'Psicorrayo', 'Ataque especial', 65, 100, 20, 'Has a 10% chance to confuse the target.', 13)
INTO ATAQUE VALUES (61, 'Rayo Burbuja', 'Ataque especial', 65, 100, 20, 'Has a 10% chance to lower the targets Speed by one stage.', 10)
INTO ATAQUE VALUES (62, 'Rayo Aurora', 'Ataque especial', 65, 100, 20, 'Has a 10% chance to lower the targets Attack by one stage.', 14)
INTO ATAQUE VALUES (63, 'Hiperrayo', 'Ataque especial', 150, 90, 5, 'User foregoes its next turn to recharge.', 1)
INTO ATAQUE VALUES (64, 'Picotazo', 'Ataque físico', 35, 100, 35, 'Inflicts regular damage with no additional effect.', 3)
INTO ATAQUE VALUES (65, 'Pico Taladro', 'Ataque físico', 80, 100, 20, 'Inflicts regular damage with no additional effect.', 3)
INTO ATAQUE VALUES (66, 'Sumisión', 'Ataque físico', 80, 80, 20, 'User receives 1/4 the damage it inflicts in recoil.', 2)
INTO ATAQUE VALUES (67, 'Patada Baja', 'Ataque físico', null, 100, 20, 'Inflicts more damage to heavier targets, with a maximum of 120 power.', 2)
INTO ATAQUE VALUES (68, 'Contraataque', 'Ataque físico', null, 100, 20, 'Inflicts twice the damage the user received from the last Ataque físico hit it took.', 2)
INTO ATAQUE VALUES (69, 'Mov. Sísmico', 'Ataque físico', null, 100, 20, 'Inflicts damage equal to the users level.', 2)
INTO ATAQUE VALUES (70, 'Fuerza', 'Ataque físico', 80, 100, 15, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (71, 'Absorber', 'Ataque especial', 20, 100, 25, 'Drains half the damage inflicted to heal the user.', 11)
INTO ATAQUE VALUES (72, 'Megaagotar', 'Ataque especial', 40, 100, 15, 'Drains half the damage inflicted to heal the user.', 11)
INTO ATAQUE VALUES (73, 'Drenadoras', 'Ataque especial', null, 90, 10, 'Seeds the target, stealing HP from it every turn.', 11)
INTO ATAQUE VALUES (74, 'Desarrollo', 'Ataque especial', null, null, 20, 'Raises the users Attack and Ataque especial Attack by one stage.', 1)
INTO ATAQUE VALUES (75, 'Hoja Afilada', 'Ataque físico', 55, 95, 25, 'Has an increased chance for a critical hit.', 11)
INTO ATAQUE VALUES (76, 'Rayo Solar', 'Ataque especial', 120, 100, 10, 'Requires a turn to charge before attacking.', 11)
INTO ATAQUE VALUES (77, 'Polvo Veneno', 'Ataque especial', null, 75, 35, 'Poisons the target.', 4)
INTO ATAQUE VALUES (78, 'Paralizador', 'Ataque especial', null, 75, 30, 'Paralyzes the target.', 11)
INTO ATAQUE VALUES (79, 'Somnífero', 'Ataque especial', null, 75, 15, 'Puts the target to sleep.', 11)
INTO ATAQUE VALUES (80, 'Danza Pétalo', 'Ataque especial', 120, 100, 10, 'Hits every turn for 2-3 turns, then confuses the user.', 11)
INTO ATAQUE VALUES (81, 'Disparo Demora', 'Ataque especial', null, 95, 40, 'Lowers the targets Speed by one stage.', 7)
INTO ATAQUE VALUES (82, 'Furia Dragón', 'Ataque especial', null, 100, 10, 'Inflicts 40 points of damage.', 15)
INTO ATAQUE VALUES (83, 'Giro Fuego', 'Ataque especial', 35, 85, 15, 'Prevents the target from fleeing and inflicts damage for 2-5 turns.', 9)
INTO ATAQUE VALUES (84, 'Impactrueno', 'Ataque especial', 40, 100, 30, 'Has a 10% chance to paralyze the target.', 12)
INTO ATAQUE VALUES (85, 'Rayo', 'Ataque especial', 90, 100, 15, 'Has a 10% chance to paralyze the target.', 12)
INTO ATAQUE VALUES (86, 'Onda Trueno', 'Ataque especial', null, 100, 20, 'Paralyzes the target.', 12)
INTO ATAQUE VALUES (87, 'Trueno', 'Ataque especial', 110, 70, 10, 'Has a 30% chance to paralyze the target.', 12)
INTO ATAQUE VALUES (88, 'Lanzarrocas', 'Ataque físico', 50, 90, 15, 'Inflicts regular damage with no additional effect.', 6)
INTO ATAQUE VALUES (89, 'Terremoto', 'Ataque físico', 100, 100, 10, 'Inflicts regular damage and can hit Dig users.', 5)
INTO ATAQUE VALUES (90, 'Fisura', 'Ataque físico', null, 30, 5, 'Causes a one-hit KO.', 5)
INTO ATAQUE VALUES (91, 'Excavar', 'Ataque físico', 80, 100, 10, 'User digs underground, dodging all attacks, and hits next turn.', 5)
INTO ATAQUE VALUES (92, 'Tóxico', 'Ataque especial', null, 90, 10, 'Badly poisons the target, inflicting more damage every turn.', 4)
INTO ATAQUE VALUES (93, 'Confusión', 'Ataque especial', 50, 100, 25, 'Has a 10% chance to confuse the target.', 13)
INTO ATAQUE VALUES (94, 'Psíquico', 'Ataque especial', 90, 100, 10, 'Has a 10% chance to lower the targets Ataque especial Defense by one stage.', 13)
INTO ATAQUE VALUES (95, 'Hipnosis', 'Ataque especial', null, 60, 20, 'Puts the target to sleep.', 13)
INTO ATAQUE VALUES (96, 'Meditación', 'Ataque especial', null, null, 40, 'Raises the users Attack by one stage.', 13)
INTO ATAQUE VALUES (97, 'Agilidad', 'Ataque especial', null, null, 30, 'Raises the users Speed by two stages.', 13)
INTO ATAQUE VALUES (98, 'Ataque Rápido', 'Ataque físico', 40, 100, 30, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (99, 'Furia', 'Ataque físico', 20, 100, 20, 'If the user is hit after using this move, its Attack rises by one stage.', 1)
INTO ATAQUE VALUES (100, 'Teletransporte', 'Ataque especial', null, null, 20, 'Immediately ends wild battles.  No effect otherwise.', 13)
INTO ATAQUE VALUES (101, 'Tinieblas', 'Ataque especial', null, 100, 15, 'Inflicts damage equal to the users level.', 8)
INTO ATAQUE VALUES (102, 'Mimético', 'Ataque especial', null, null, 10, 'Copies the targets last used move.', 1)
INTO ATAQUE VALUES (103, 'Chirrido', 'Ataque especial', null, 85, 40, 'Lowers the targets Defense by two stages.', 1)
INTO ATAQUE VALUES (104, 'Doble Equipo', 'Ataque especial', null, null, 15, 'Raises the users evasion by one stage.', 1)
INTO ATAQUE VALUES (105, 'Recuperación', 'Ataque especial', null, null, 10, 'Heals the user by half its max HP.', 1)
INTO ATAQUE VALUES (106, 'Fortaleza', 'Ataque especial', null, null, 30, 'Raises the users Defense by one stage.', 1)
INTO ATAQUE VALUES (107, 'Reducción', 'Ataque especial', null, null, 10, 'Raises the users evasion by two stages.', 1)
INTO ATAQUE VALUES (108, 'Pantalla de Humo', 'Ataque especial', null, 100, 20, 'Lowers the targets accuracy by one stage.', 1)
INTO ATAQUE VALUES (109, 'Rayo Confuso', 'Ataque especial', null, 100, 10, 'Confuses the target.', 8)
INTO ATAQUE VALUES (110, 'Refugio', 'Ataque especial', null, null, 40, 'Raises the users Defense by one stage.', 10)
INTO ATAQUE VALUES (111, 'Rizo Defensa', 'Ataque especial', null, null, 40, 'Raises users Defense by one stage.', 1)
INTO ATAQUE VALUES (112, 'Barrera', 'Ataque especial', null, null, 20, 'Raises the users Defense by two stages.', 13)
INTO ATAQUE VALUES (113, 'Pantalla de Luz', 'Ataque especial', null, null, 30, 'Reduces damage from Ataque especial attacks by 50% for five turns.', 13)
INTO ATAQUE VALUES (114, 'Niebla', 'Ataque especial', null, null, 30, 'Resets all Pokémons stats, accuracy, and evasion.', 14)
INTO ATAQUE VALUES (115, 'Reflejo', 'Ataque especial', null, null, 20, 'Reduces damage from Ataque físico attacks by half.', 13)
INTO ATAQUE VALUES (116, 'Foco Energía', 'Ataque especial', null, null, 30, 'Increases the users chance to score a critical hit.', 1)
INTO ATAQUE VALUES (117, 'Venganza', 'Ataque físico', null, null, 10, 'User waits for two turns, then hits back for twice the damage it took.', 1)
INTO ATAQUE VALUES (118, 'Metrónomo', 'Ataque especial', null, null, 10, 'Randomly selects and uses any move in the game.', 1)
INTO ATAQUE VALUES (119, 'Mov. Espejo', 'Ataque especial', null, null, 20, 'Uses the targets last used move.', 3)
INTO ATAQUE VALUES (120, 'Autodestrucción', 'Ataque físico', 200, 100, 5, 'User faints.', 1)
INTO ATAQUE VALUES (121, 'Bomba Huevo', 'Ataque físico', 100, 75, 10, 'Inflicts regular damage with no additional effect.', 1)
INTO ATAQUE VALUES (122, 'Lengüetazo', 'Ataque físico', 30, 100, 30, 'Has a 30% chance to paralyze the target.', 8)
INTO ATAQUE VALUES (123, 'Polución', 'Ataque especial', 30, 70, 20, 'Has a 40% chance to poison the target.', 4)
INTO ATAQUE VALUES (125, 'Hueso Palo', 'Ataque físico', 65, 85, 20, 'Has a 10% chance to make the target flinch.', 5)
INTO ATAQUE VALUES (124, 'Residuos', 'Ataque especial', 65, 100, 20, 'Has a 30% chance to poison the target.', 4)
INTO ATAQUE VALUES (126, 'Llamarada', 'Ataque especial', 110, 85, 5, 'Has a 10% chance to burn the target.', 9)
INTO ATAQUE VALUES (127, 'Cascada', 'Ataque físico', 80, 100, 15, 'Has a 20% chance to make the target flinch.', 10)
INTO ATAQUE VALUES (128, 'Tenaza', 'Ataque físico', 35, 85, 15, 'Prevents the target from fleeing and inflicts damage for 2-5 turns.', 10)
INTO ATAQUE VALUES (129, 'Rapidez', 'Ataque especial', 60, null, 20, 'Never misses.', 1)
INTO ATAQUE VALUES (130, 'Cabezazo', 'Ataque físico', 130, 100, 10, 'Raises the users Defense by one stage.  User charges for one turn before attacking.', 1)
INTO ATAQUE VALUES (131, 'Clavo Cañón', 'Ataque físico', 20, 100, 15, 'Hits 2-5 times in one turn.', 1)
INTO ATAQUE VALUES (132, 'Restricción', 'Ataque físico', 10, 100, 35, 'Has a 10% chance to lower the targets Speed by one stage.', 1)
INTO ATAQUE VALUES (133, 'Amnesia', 'Ataque especial', null, null, 20, 'Raises the users Ataque especial Defense by two stages.', 13)
INTO ATAQUE VALUES (134, 'Kinético', 'Ataque especial', null, 80, 15, 'Lowers the targets accuracy by one stage.', 13)
INTO ATAQUE VALUES (135, 'Amortiguador', 'Ataque especial', null, null, 10, 'Heals the user by half its max HP.', 1)
INTO ATAQUE VALUES (136, 'Pat. Salto Alta', 'Ataque físico', 130, 90, 10, 'If the user misses, it takes half the damage it would have inflicted in recoil.', 2)
INTO ATAQUE VALUES (137, 'Deslumbrar', 'Ataque especial', null, 100, 30, 'Paralyzes the target.', 1)
INTO ATAQUE VALUES (138, 'Come Sueños', 'Ataque especial', 100, 100, 15, 'Only works on sleeping Pokémon.  Drains half the damage inflicted to heal the user.', 13)
INTO ATAQUE VALUES (139, 'Gas Venenoso', 'Ataque especial', null, 90, 40, 'Poisons the target.', 4)
INTO ATAQUE VALUES (140, 'Presa', 'Ataque físico', 15, 85, 20, 'Hits 2-5 times in one turn.', 1)
INTO ATAQUE VALUES (141, 'Chupavidas', 'Ataque físico', 20, 100, 15, 'Drains half the damage inflicted to heal the user.', 7)
INTO ATAQUE VALUES (142, 'Beso Amoroso', 'Ataque especial', null, 75, 10, 'Puts the target to sleep.', 1)
INTO ATAQUE VALUES (143, 'Ataque Aéreo', 'Ataque físico', 140, 90, 5, 'User charges for one turn before attacking.  Has a 30% chance to make the target flinch.', 3)
INTO ATAQUE VALUES (144, 'Transformación', 'Ataque especial', null, null, 10, 'User becomes a copy of the target until it leaves battle.', 1)
INTO ATAQUE VALUES (145, 'Burbuja', 'Ataque especial', 40, 100, 30, 'Has a 10% chance to lower the targets Speed by one stage.', 10)
INTO ATAQUE VALUES (147, 'Espora', 'Ataque especial', null, 100, 15, 'Puts the target to sleep.', 11)
INTO ATAQUE VALUES (146, 'Puño Mareo', 'Ataque físico', 70, 100, 10, 'Has a 20% chance to confuse the target.', 1)
INTO ATAQUE VALUES (148, 'Destello', 'Ataque especial', null, 100, 20, 'Lowers the targets accuracy by one stage.', 1)
INTO ATAQUE VALUES (149, 'Psicoonda', 'Ataque especial', null, 100, 15, 'Inflicts damage between 50% and 150% of the users level.', 13)
INTO ATAQUE VALUES (150, 'Salpicadura', 'Ataque especial', null, null, 40, 'Does nothing.', 1)
INTO ATAQUE VALUES (151, 'Armadura Ácida', 'Ataque especial', null, null, 20, 'Raises the users Defense by two stages.', 4)
INTO ATAQUE VALUES (152, 'Martillazo', 'Ataque físico', 100, 90, 10, 'Has an increased chance for a critical hit.', 10)
INTO ATAQUE VALUES (153, 'Explosión', 'Ataque físico', 250, 100, 5, 'User faints.', 1)
INTO ATAQUE VALUES (154, 'Golpes Furia', 'Ataque físico', 18, 80, 15, 'Hits 2-5 times in one turn.', 1)
INTO ATAQUE VALUES (155, 'Huesomerang', 'Ataque físico', 50, 90, 10, 'Hits twice in one turn.', 5)
INTO ATAQUE VALUES (156, 'Descanso', 'Ataque especial', null, null, 10, 'User sleeps for two turns, completely healing itself.', 13)
INTO ATAQUE VALUES (157, 'Avalancha', 'Ataque físico', 75, 90, 10, 'Has a 30% chance to make the target flinch.', 6)
INTO ATAQUE VALUES (158, 'Hipercolmillo', 'Ataque físico', 80, 90, 15, 'Has a 10% chance to make the target flinch.', 1)
INTO ATAQUE VALUES (159, 'Afilar', 'Ataque especial', null, null, 30, 'Raises the users Attack by one stage.', 1)
INTO ATAQUE VALUES (160, 'Conversión', 'Ataque especial', null, null, 30, 'Users type changes to the type of one of its moves at random.', 1)
INTO ATAQUE VALUES (161, 'Triataque', 'Ataque especial', 80, 100, 10, 'Has a 20% chance to burn, freeze, or paralyze the target.', 1)
INTO ATAQUE VALUES (162, 'Superdiente', 'Ataque físico', null, 90, 10, 'Inflicts damage equal to half the targets HP.', 1)
INTO ATAQUE VALUES (163, 'Cuchillada', 'Ataque físico', 70, 100, 20, 'Has an increased chance for a critical hit.', 1)
INTO ATAQUE VALUES (164, 'Sustituto', 'Ataque especial', null, null, 10, 'Transfers 1/4 of the users max HP into a doll, protecting the user from further damage or Ataque especial changes until it breaks.', 1)
INTO ATAQUE VALUES (165, 'Combate', 'Ataque físico', 50, null, null, 'User takes 1/4 its max HP in recoil.', 1)
SELECT 1 FROM DUAL;
