--Insertar a la tabla Habilidad
INSERT ALL
INTO Habilidad VALUES (1, 'Hielo Abrazador', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (2, 'Fuego Abrazador','Soy muy flojo para copiar mucho jaja saludos' )
INTO Habilidad VALUES (3, 'Ola Abrazadora', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (4, 'Amor Abrazador', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (5, 'FUCK ME HARDER', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (6, 'Fuego intenso', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (7, 'Fuego lento', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (8, 'Fuego Abrazador', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (9, 'estaca Abrazadora', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (10, 'espada mortal', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (11, 'rafaga Abrazadora', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (12, 'tormenta Abrazadora', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (13, 'tormenta de hielo', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (14, 'golpe Abrazador', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (15, 'Fuego Abrazador', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (16, 'desaparecer', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (17, 'excavar', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (18, 'tromenta de arena', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (19, 'Fuerza Bruta', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (20, 'Fuerza normal', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (21, 'Fuerza debil', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (22, 'golpe Brutal', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (23, 'patada Brutal', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (24, 'espada Bruta', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (25, 'latigo Brutal', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (26, 'Cabezaso Brutal', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (27, 'Cortar', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (28, 'Volar', 'Soy muy flojo para copiar mucho jaja saludos')
INTO Habilidad VALUES (29, 'Quemar', 'Soy muy flojo para copiar mucho jaja saludos')
SELECT 1 FROM DUAL;
