--Insertar a la tabla Habilidad
INSERT ALL
INTO Habilidad VALUES (1, 'Water Absorb', 'Recupera PS al recibir ataques de tipo agua')
INTO Habilidad VALUES (2, 'Volt Absorb','Recupera PS al recibir ataques de tipo eléctrico.' )
INTO Habilidad VALUES (3, 'Flash Fire', 'Potencia movimientos de tipo fuego si ha sufrido antes alguno')
INTO Habilidad VALUES (4, 'Cloud Nine', 'Anula los efectos del tiempo atmosférico')
INTO Habilidad VALUES (5, 'Guts', 'Sube el ataque si sufre un problema de estado.')
INTO Habilidad VALUES (6, 'Battle Armor', 'Bloquea los golpes críticos.')
INTO Habilidad VALUES (7, 'Truant', 'El Pokémon no atacará en turnos consecutivos.')
INTO Habilidad VALUES (8, 'Air Lock', 'Anula los efectos del tiempo atmosférico.')
INTO Habilidad VALUES (9, 'Rock Head', 'Impide que el Pokémon se dañe con sus movimientos')
INTO Habilidad VALUES (10, 'Cacophony', 'Evita ataques de sonido')
INTO Habilidad VALUES (11, 'Color Change', 'Adopta el tipo del último movimiento del que se es blanco.')
INTO Habilidad VALUES (12, 'Shell Armor', 'Bloquea los golpes críticos.')
INTO Habilidad VALUES (13, 'Sand Stream', 'Crea una tormenta de arena en el combate.')
INTO Habilidad VALUES (14, 'Chlorophyll', 'Sube la velocidad cuando hay sol.')
INTO Habilidad VALUES (15, 'Hyper Cutter', 'Evita que disminuya el ataque.')
INTO Habilidad VALUES (16, 'Flame Body', 'Puede quemar al mínimo contacto.')
INTO Habilidad VALUES (17, 'Clear Body', 'Evita que bajen las características.')
INTO Habilidad VALUES (18, 'Rain Dish', 'Recupera PS de forma gradual cuando llueve.')
INTO Habilidad VALUES (19, 'Natural Cure', 'Cura problemas de estado al cambiar de Pokémon.')
INTO Habilidad VALUES (20, 'Oblivious', 'Evita que el Pokémon sea atraído o provocado.')
INTO Habilidad VALUES (21, 'Serene Grace', 'Aumenta la probabilidad de que haya efectos secundarios.')
INTO Habilidad VALUES (22, 'Effect Spore', 'Puede dormir, envenenar o paralizar al contacto.')
INTO Habilidad VALUES (23, 'Static', 'Puede paralizar al mínimo contacto.')
INTO Habilidad VALUES (24, 'Pure Power', 'Aumenta el ataque.')
INTO Habilidad VALUES (25, 'Swarm', 'Potencia los ataques de tipo bicho en un apuro')
INTO Habilidad VALUES (26, 'Hustle', 'Aumenta el ataque, pero reduce la precisión.')
INTO Habilidad VALUES (27, 'Marvel Scale', 'Sube la defensa si sufre un problema de estado.')
INTO Habilidad VALUES (28, 'Magma Armor', 'Evita la congelación')
INTO Habilidad VALUES (29, 'Overgrow', 'Potencia los ataques de tipo planta en un apuro.')
SELECT 1 FROM DUAL;
